version: "3.7"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    image: caddy:cloudflare
    container_name: frontend
    hostname: frontend
    env_file:
      - .env
    ports:
      - 80:80
      - 443:443
    volumes:
      - caddy_data:/data
      - ./Caddyfile:/etc/caddy/Caddyfile

  backend1:
    build:
      context: .
      dockerfile: Dockerfile.backend1
    container_name: backend-1
    command: ["npm", "run", "start"]
    env_file:
      - .env
    depends_on:
      - database

  backend2:
    build:
      context: .
      dockerfile: Dockerfile.backend2
    container_name: backend-2
    command: ["npm", "run", "start"]
    env_file:
      - .env
    depends_on:
      - database

  database:
    image: postgres:16.1-alpine
    restart: always
    container_name: database
    env_file:
      - .env
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  caddy_data:
  pgdata:
