services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    image: caddy:cloudflare
    container_name: wishub-frontend
    hostname: frontend
    restart: always
    env_file:
      - .env
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: wishub-backend
    command: ["pnpm", "start"]
    restart: always
    env_file:
      - .env
    platform: linux/amd64

  database:
    image: postgres:16.1-alpine
    restart: always
    container_name: wishub-database
    env_file:
      - .env
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - ./.postgtres:/var/lib/postgresql/data
