services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wishub-app
    restart: always
    environment:
      DATABASE_URL: "postgresql://wishub:wishub@database:5432/wishub"

  database:
    image: postgres:17.2-alpine
    restart: always
    container_name: wishub-database
    environment:
      POSTGRES_DB: "wishub"
      POSTGRES_USER: "wishub"
      POSTGRES_PASSWORD: "wishub"
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - ./.postgtres:/var/lib/postgresql/data
